name: Conectar a instancia EC2

on:
  push:
    branches:
      - develop

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar a instancia EC2
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          echo "${{ secrets.SSH_SECRET }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ec2-user@18.229.135.176
