name: Ejecutar Docker en instancia EC2

on:
  push:
    branches:
      - develop

jobs:
  run_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Construir imagen de Docker
        run: |
          docker build -t mi-app-fastapi .
          docker images

      - name: Conectar a instancia EC2 y ejecutar Docker
        run: |
          ssh -i conectar-api-key-pairs.pem ec2-user@18.229.135.176 "docker run mi-app-fastapi"
