name: Conectar a EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: Configurar credenciales de AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Conectar a EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: 18.229.135.176
          username: ec2-user
          key: ${{ secrets.SSH_SECRET }}
          script: |
            # Comandos a ejecutar en la instancia de EC2
            echo "¡Conexión exitosa!"
            # Ejemplo adicional: ejecutar un comando de shell en la instancia
            ssh ec2-user@18.229.135.176 "ls -al"
