name: Conectar a EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 18.229.135.176
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker pull your-docker-image-tag
            docker run -d --name your-container-name -p 8000:8000 your-docker-image-tag
