name: Conexión a EC2 con SSH

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar entorno SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa <EC2-INSTANCE-IP> >> ~/.ssh/known_hosts

      - name: Conectar a la instancia EC2
        run: |
          docker build -t mi-app-fastapi 
          docker run -d --name conectarapi_user mi-app-fastapi
          ssh -i ~/.ssh/id_rsa ec2-user@18.229.135.176 "docker stop conectarapi_user"
